// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TuCredito.Models;

public partial class Cuota
{
    public int IdCuota { get; set; }

    public int IdPrestamo { get; set; }

    public int NroCuota { get; set; }

    public decimal Monto { get; set; }

    public DateOnly FecVto { get; set; }

    public int IdEstado { get; set; }

    public decimal? Interes { get; set; }

    public virtual EstadoCuotum IdEstadoNavigation { get; set; }

    public virtual Prestamo IdPrestamoNavigation { get; set; }

    public virtual ICollection<Pago> Pagos { get; set; } = new List<Pago>();
}