// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TuCredito.Models;

public partial class Garante
{
    public int IdGarante { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string Telefono { get; set; }

    public string Domicilio { get; set; }

    public string Correo { get; set; }

    public bool EsActivo { get; set; }

    public virtual ICollection<Prestatario> Prestatarios { get; set; } = new List<Prestatario>();
}