// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TuCredito.Models;

public partial class MediosDePago
{
    public int IdMedioPago { get; set; }

    public string Descripcion { get; set; }

    public string Moneda { get; set; }

    public virtual ICollection<Pago> Pagos { get; set; } = new List<Pago>();
}