// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TuCredito.Models;

public partial class AuditLog
{
    public int Id { get; set; }

    public string EntityName { get; set; }

    public string Action { get; set; }

    public DateTime Timestamp { get; set; }

    public string UserId { get; set; }

    public string Changes { get; set; }

    public string EntityId { get; set; }
}