// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TuCredito.Models;

public partial class Documento
{
    public int IdDocumento { get; set; }

    public string EntidadTipo { get; set; }

    public int EntidadId { get; set; }

    public string TipoDocumento { get; set; }

    public string NombreOriginal { get; set; }

    public string RutaStorage { get; set; }

    public string ContentType { get; set; }

    public DateTime FechaSubida { get; set; }

    public int SubidoPor { get; set; }

    public bool Activo { get; set; }
}