// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TuCredito.Models;

public partial class EstadosCuota
{
    public int IdEstado { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<Cuota> Cuota { get; set; } = new List<Cuota>();
}