// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TuCredito.Models;

public partial class Pago
{
    public int IdPago { get; set; }

    public int IdCuota { get; set; }

    public DateTime FecPago { get; set; }

    public int IdMedioPago { get; set; }

    public decimal Saldo { get; set; }

    public string Estado { get; set; }

    public decimal Monto { get; set; }

    public string Observaciones { get; set; }
<<<<<<< HEAD
    public string Estado { get; set; } // registrado - eliminado 
=======
>>>>>>> 6019ec3a5a100a570682392315ff7b5220de3047

    public virtual Cuota IdCuotaNavigation { get; set; }

    public virtual MediosDePago IdMedioPagoNavigation { get; set; }
}