// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TuCredito.Models;

public partial class Pago
{
    public int IdPago { get; set; }

    public int IdCuota { get; set; }

    public DateTime FecPago { get; set; }

    public int IdMedioPago { get; set; }

    public decimal Monto { get; set; }

    public string Observaciones { get; set; }
    public string Estado { get; set; }

    public virtual Cuota IdCuotaNavigation { get; set; }

    public virtual MediosDePago IdMedioPagoNavigation { get; set; }
}