// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TuCredito.Models;

public partial class Prestatario
{
    public int Dni { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string Telefono { get; set; }

    public string Domicilio { get; set; }

    public string Correo { get; set; }

    public bool EsActivo { get; set; }

    public int? IdGarante { get; set; }

    public virtual Garante IdGaranteNavigation { get; set; }

    public virtual ICollection<Prestamo> Prestamos { get; set; } = new List<Prestamo>();
}