// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TuCredito.Models;

public partial class Prestamo
{
    public int IdPrestamo { get; set; }

    public int IdPrestamista { get; set; }

    public int DniPrestatario { get; set; }

    public decimal MontoOtorgado { get; set; }

    public int CantidadCtas { get; set; }

    public int IdEstado { get; set; }

    public decimal TasaInteres { get; set; }

    public DateTime? FechaFinEstimada { get; set; }

    public DateTime FechaOtorgamiento { get; set; }

    public DateTime Fec1erVto { get; set; }

    public int IdSistAmortizacion { get; set; }

    public virtual ICollection<Cuota> Cuota { get; set; } = new List<Cuota>();

    public virtual Prestatario DniPrestatarioNavigation { get; set; }

    public virtual EstadoPrestamo IdEstadoNavigation { get; set; }

    public virtual Prestamista IdPrestamistaNavigation { get; set; }

    public virtual SistAmortizacion IdSistAmortizacionNavigation { get; set; }
}