// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace TuCredito.Models;

public partial class TuCreditoContext : DbContext
{
    public TuCreditoContext(DbContextOptions<TuCreditoContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Cuota> Cuotas { get; set; }

    public virtual DbSet<EstadosCuota> EstadosCuotas { get; set; }

    public virtual DbSet<EstadosPrestamo> EstadosPrestamos { get; set; }

    public virtual DbSet<Garante> Garantes { get; set; }

    public virtual DbSet<MediosDePago> MediosDePagos { get; set; }

    public virtual DbSet<Pago> Pagos { get; set; }

    public virtual DbSet<Prestamista> Prestamistas { get; set; }

    public virtual DbSet<Prestamo> Prestamos { get; set; }

    public virtual DbSet<Prestatario> Prestatarios { get; set; }

    public virtual DbSet<SistAmortizacion> SistAmortizacions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Cuota>(entity =>
        {
            entity.HasKey(e => e.IdCuota).HasName("PK__Cuotas__9BE53C1831FFE543");

            entity.Property(e => e.IdCuota).HasColumnName("idCuota");
            entity.Property(e => e.FecVto).HasColumnName("Fec_Vto");
            entity.Property(e => e.IdEstado).HasColumnName("idEstado");
            entity.Property(e => e.IdPrestamo).HasColumnName("idPrestamo");
            entity.Property(e => e.Interes).HasColumnType("decimal(12, 2)");
            entity.Property(e => e.Monto).HasColumnType("decimal(12, 2)");
            entity.Property(e => e.NroCuota).HasColumnName("nroCuota");

            entity.HasOne(d => d.IdEstadoNavigation).WithMany(p => p.Cuota)
                .HasForeignKey(d => d.IdEstado)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Cuotas_Estado");

            entity.HasOne(d => d.IdPrestamoNavigation).WithMany(p => p.Cuota)
                .HasForeignKey(d => d.IdPrestamo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Cuotas_Prestamo");
        });

        modelBuilder.Entity<EstadosCuota>(entity =>
        {
            entity.HasKey(e => e.IdEstado).HasName("PK__Estados___62EA894A9994D877");

            entity.ToTable("Estados_Cuotas");

            entity.Property(e => e.IdEstado).HasColumnName("idEstado");
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("descripcion");
        });

        modelBuilder.Entity<EstadosPrestamo>(entity =>
        {
            entity.HasKey(e => e.IdEstado).HasName("PK__Estados___62EA894AB4FF848B");

            entity.ToTable("Estados_Prestamos");

            entity.Property(e => e.IdEstado).HasColumnName("idEstado");
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("descripcion");
        });

        modelBuilder.Entity<Garante>(entity =>
        {
            entity.HasKey(e => e.IdGarante).HasName("PK__Garantes__071AE8B616089AC1");

            entity.Property(e => e.IdGarante).HasColumnName("idGarante");
            entity.Property(e => e.Apellido)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("apellido");
            entity.Property(e => e.Correo)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("correo");
            entity.Property(e => e.Domicilio)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("domicilio");
            entity.Property(e => e.EsActivo).HasColumnName("esActivo");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nombre");
            entity.Property(e => e.Telefono)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("telefono");
        });

        modelBuilder.Entity<MediosDePago>(entity =>
        {
            entity.HasKey(e => e.IdMedioPago).HasName("PK__MediosDe__7AE6AD6DD564E703");

            entity.ToTable("MediosDePago");

            entity.Property(e => e.IdMedioPago).HasColumnName("idMedio_Pago");
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("descripcion");
            entity.Property(e => e.Moneda)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("moneda");
        });

        modelBuilder.Entity<Pago>(entity =>
        {
            entity.HasKey(e => e.IdPago).HasName("PK__Pagos__BD2295ADF77BD806");

            entity.Property(e => e.IdPago).HasColumnName("idPago");
            entity.Property(e => e.FecPago).HasColumnName("Fec_Pago");
            entity.Property(e => e.IdCuota).HasColumnName("idCuota");
            entity.Property(e => e.IdMedioPago).HasColumnName("idMedioPago");
            entity.Property(e => e.Monto).HasColumnType("decimal(12, 2)");
            entity.Property(e => e.Observaciones)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.HasOne(d => d.IdCuotaNavigation).WithMany(p => p.Pagos)
                .HasForeignKey(d => d.IdCuota)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Pagos_Cuota");

            entity.HasOne(d => d.IdMedioPagoNavigation).WithMany(p => p.Pagos)
                .HasForeignKey(d => d.IdMedioPago)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Pagos_MedioPago");
        });

        modelBuilder.Entity<Prestamista>(entity =>
        {
            entity.ToTable("Prestamistas", "dbo");

            entity.HasKey(e => e.Id).HasName("PK__Prestami__3213E83F76C70EAD");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Apellido)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("apellido");
            entity.Property(e => e.ContraseniaHash)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("contraseniaHash");
            entity.Property(e => e.Correo)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("correo");
            entity.Property(e => e.EsActivo).HasColumnName("esActivo");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nombre");
            entity.Property(e => e.Usuario)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("usuario");
        });

        modelBuilder.Entity<Prestamo>(entity =>
        {
            entity.HasKey(e => e.IdPrestamo).HasName("PK__Prestamo__A4876C130559895B");

            entity.Property(e => e.IdPrestamo).HasColumnName("idPrestamo");
            entity.Property(e => e.CantidadCtas).HasColumnName("Cantidad_ctas");
            entity.Property(e => e.DniPrestatario).HasColumnName("DNI_Prestatario");
            entity.Property(e => e.Fec1erVto).HasColumnName("Fec_1erVto");
            entity.Property(e => e.FechaFinEstimada).HasColumnName("fechaFinEstimada");
            entity.Property(e => e.FechaOtorgamiento).HasColumnName("fechaOtorgamiento");
            entity.Property(e => e.IdEstado).HasColumnName("idEstado");
            entity.Property(e => e.IdPrestamista).HasColumnName("idPrestamista");
            entity.Property(e => e.IdSistAmortizacion).HasColumnName("idSistAmortizacion");
            entity.Property(e => e.MontoOtorgado).HasColumnType("decimal(12, 2)");
            entity.Property(e => e.TasaInteres)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("tasaInteres");

            entity.HasOne(d => d.DniPrestatarioNavigation).WithMany(p => p.Prestamos)
                .HasForeignKey(d => d.DniPrestatario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Prestamos_Prestatario");

            entity.HasOne(d => d.IdEstadoNavigation).WithMany(p => p.Prestamos)
                .HasForeignKey(d => d.IdEstado)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Prestamos_Estado");

            entity.HasOne(d => d.IdPrestamistaNavigation).WithMany(p => p.Prestamos)
                .HasForeignKey(d => d.IdPrestamista)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Prestamos_Prestamista");

            entity.HasOne(d => d.IdSistAmortizacionNavigation).WithMany(p => p.Prestamos)
                .HasForeignKey(d => d.IdSistAmortizacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Prestamos_SistAmort");
        });

        modelBuilder.Entity<Prestatario>(entity =>
        {
            entity.HasKey(e => e.Dni).HasName("PK__Prestata__C035B8DC99C9F1D5");

            entity.Property(e => e.Dni)
                .ValueGeneratedNever()
                .HasColumnName("DNI");
            entity.Property(e => e.Apellido)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("apellido");
            entity.Property(e => e.Correo)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("correo");
            entity.Property(e => e.Domicilio)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("domicilio");
            entity.Property(e => e.EsActivo).HasColumnName("esActivo");
            entity.Property(e => e.IdGarante).HasColumnName("idGarante");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nombre");
            entity.Property(e => e.Telefono)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("telefono");

            entity.HasOne(d => d.IdGaranteNavigation).WithMany(p => p.Prestatarios)
                .HasForeignKey(d => d.IdGarante)
                .HasConstraintName("FK_Prestatario_Garante");
        });

        modelBuilder.Entity<SistAmortizacion>(entity =>
        {
            entity.HasKey(e => e.IdSistAmortizacion).HasName("PK__SistAmor__4E23826BE7F3D817");

            entity.ToTable("SistAmortizacion");

            entity.Property(e => e.IdSistAmortizacion).HasColumnName("idSistAmortizacion");
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("descripcion");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}